### ISSUE TITLE
Calculating Quantity in Grocery List

### ISSUE THREAD

**Issue by Annarhysa** [Annarhysa/CarbonCart#5]
Prompting user to give quantity of items that they would be purchasing

**Comment by Prithvi2310** [comment]
- [x] regex feature to extract digits in text 
- [ ] intimating users that we do not have the item in the dataset

**Comment by Annarhysa** [comment]
- [ ] Check why some items that are present in database are not being asked for specific data item

**Comment by Annarhysa** [comment]
- [x] Typo checking using llms or custom json
- [ ] Actual Camera Images of Bills
